### ISSUE TITLE
「温暖饭团」少了一个 「流行·厌恶」的标签

### ISSUE THREAD

**Issue by Kayton1** [AnYiEE/touhou-mystia-izakaya-assistant#10]
![1](https://github.com/user-attachments/assets/ac7f9ef7-20be-4ba3-b554-cc5d96c005a1)
![2](https://github.com/user-attachments/assets/8d5305c3-32ef-4ff0-b583-87b652f45ebe)
![3](https://github.com/user-attachments/assets/6fc73f18-dee5-4ea2-987e-f2315068729e)
感谢作者，非常好用工具使我一天营业14小时🥰🥰🥰
还有一个就是，能不能直接不显示含有厌恶标签的菜捏，那个厌恶标签亮起来感觉不是很显眼🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by AnYiEE** [comment]
流行趋势是游戏内动态生成的（游戏内报纸会有报道），并不是温暖饭团本身有这个标签，而是你游戏里的流行趋势正流行厌恶着温暖饭团的某个标签。

小助手同样可以动态地设置流行趋势（在“设置”页面里有相关设置项），设置之后你就可以看到温暖饭团会有你提到的标签了。

**Comment by Kayton1** [comment]
原来如此，感谢解答！🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by AnYiEE** [comment]
> 能不能直接不显示含有厌恶标签的菜

流行厌恶并不一定是负面的，有的人喜欢流行厌恶。
